-- 0036_cloud_only_seed_app_review_activity_data.sql — placeholder for the cloud-only migration recorded as version 20260905012059
-- ("seed_app_review_activity_data").
--
-- WHY THIS FILE IS EMPTY OF DDL
-- The App Review preparation work on 2026-09-05 was applied directly to the cloud project,
-- so the remote `supabase_migrations.schema_migrations` table has a timestamp-versioned row
-- with no local file. That is the exact condition that turns the "Supabase Preview" GitHub
-- check red (see CLAUDE.md > Conventions and `pnpm check:preview`). This file exists so
-- local and remote migration history agree after the remote row is relabeled to 0036:
--
--   update supabase_migrations.schema_migrations set version='0036' where version='20260905012059';
--
-- It deliberately does NOT reproduce the original SQL:
--   * that statement seeds bookings, messages and sessions belonging to the reviewer demo
--     accounts above. It references those accounts' ids, so it is meaningless on a database
--     that does not have them (see APP_REVIEW_TICKETS.md T8).
--
-- Intentionally a no-op on every database. Safe to apply locally and on preview branches.
